# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Blog
    url: /post
    weight: 11
  - name: Services
    url: /services
    weight: 12
  - name: Testimonials
    url: /testimonials
    weight: 13
  - name: CV
    url: uploads/resume.pdf
    weight: 20
